name: CI/CD for Stock Predictor

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: sudo apt-get install docker.io -y

      - name: Build and run container
        run: |
          docker build -t stock-predictor .
          docker run -d -p 5000:5000 stock-predictor

