name: CI/CD for Stock Predictor

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove --purge docker docker-engine docker.io containerd runc -y
          sudo apt-get autoremove -y
          sudo apt-get clean
          
          # Install required dependencies
          sudo apt-get install -y ca-certificates curl gnupg lsb-release

          # Add Docker's official GPG key and repository
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          # Update and install Docker
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build and run container
        run: |
          docker build -t stock-predictor .
          docker run -d -p 5000:5000 stock-predictor
